### ISSUE TITLE
using the library

### ISSUE THREAD

**Issue by balasivagnanam** [roomorama/Caldroid#122]
I would like to use this calendar view in my app. I am new to android and this is my first app.

I tried importing this to library folder, copied the file contents into my project, searched for jar. After searching on how to reference library projects, I found this one http://www.vogella.com/tutorials/AndroidLibraryProjects/article.html and tried to do the same.. So I tried to create a project with the files supplied in the library folder I get error

import com.caldroid.R;  - The import com.caldroid.R cannot be resolved

When I tried to use the sample demo I was getting the same error... 

import com.roomorama.caldroid.CaldroidFragment; - The import com.roomorama cannot be resolved
import com.roomorama.caldroid.CaldroidListener;  - The import com.roomorama cannot be resolved

Please help me.. Very sorry if my question is stupid. I am new and this is the first time I am trying to use a library.

**Comment by neonwarge04** [comment]
Hi, I know my post is kind of late but I have encountered similar problem and this fixed my problem by creating a new Android Project without activity and manifest file, but I didn't mark the project as a library since I am loading the demo file. (First off, I used the source files on this link: https://github.com/roomorama/Caldroid/releases/tag/eclipse_project). At first I missed this on the Read Me but this one has all the files compatible with eclipse. Then I went to project properties > android > Library section > add > I went to add the Caldroid library (This will not appear if the project is not 'Mark as Library'). I added that and I cleaned and rebuilt the entire workspace. Now it no longer give resolution error on R, no longer encounter import resolution problem.

I hope this helps you. I can now see the Calendar and this is exactly what I need for my project. 

Cheers.
Neon
