### ISSUE TITLE
Unable to restore fragment state on screen rotation

### ISSUE THREAD

**Issue by MarcusJacobsson** [roomorama/Caldroid#242]
I'm following the instructions to restore the fragment state on screen rotation, but it does not seem to work. 

I set up my fragment like this

    caldroidFragment = new CaldroidFragment();
    Bundle args = new Bundle();
    Calendar cal = Calendar.getInstance();
    args.putInt(CaldroidFragment.MONTH, cal.get(Calendar.MONTH) + 1);
    args.putInt(CaldroidFragment.YEAR, cal.get(Calendar.YEAR));
    caldroidFragment.setArguments(args);
    android.support.v4.app.FragmentTransaction t = getSupportFragmentManager().beginTransaction();
    t.replace(R.id.content_frame, caldroidFragment);
    t.commit();

and I save state like this

    @Override
    public void onSaveInstanceState(Bundle outState, PersistableBundle outPersistentState) {
        super.onSaveInstanceState(outState, outPersistentState);
        if (caldroidFragment != null) {
            caldroidFragment.saveStatesToKey(outState, "CALDROID_SAVED_STATE");
        }
    }

and restore state like this

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        setUpComponents();
        if (savedInstanceState != null) {
            if (caldroidFragment != null){
                caldroidFragment.restoreStatesFromKey(savedInstanceState,
                        "CALDROID_SAVED_STATE");
            }

        }
    }

But the result is an empty fragment, only showing headers but no text view dates as when you created it from scratch. See below image.

Before rotation:

![2015-03-22 19 20 54](https://cloud.githubusercontent.com/assets/3079470/6770964/08240a1e-d0d1-11e4-856c-38c2fb90f72c.png)

After rotation:

![2015-03-22 19 20 02](https://cloud.githubusercontent.com/assets/3079470/6770960/facba214-d0d0-11e4-9d6b-d8a3216a410c.png)

What am I doing wrong?

**Comment by thomasdao** [comment]
You may need to create a new CaldroidFragment instead of using the previous one

**Comment by MarcusJacobsson** [comment]
I did that, and the fragment content is now persisting. Another problem tho: the size of the TextViews in the different grid cells get reduced when I switch from Portrait -> Landscape -> Portrait. Is there a way to reset it to the "default" gridview cell size?

**Comment by thomasdao** [comment]
You can use 

```java
Bundle args = new Bundle();
args.putBoolean(CaldroidFragment.SQUARE_TEXT_VIEW_CELL, true);
caldroidFragment.setArguments(args);

```

**Comment by hagabaka** [comment]
I have a similar problem although my setup is somewhat different. I wanted caldroid to use a custom style in portrait only, with reduced cell padding. I implemented it by placing the caldroid fragment inside the layout XMLs, where the portrait layout contains my subclass caldroid fragment using the custom style. This means I can't use setArguments since "fragment is already active", so I just set parameters using the available set methods.

Caldroid itself is contained in another fragment which is contained in an activity. I used to recreate caldroid's parent fragment on screen rotation, and this setup worked. But now I'm trying to preserve the parent fragment's state using FragmentManager.{put,get}Fragment, and after the fragment is restored, caldroid will have blank contents except the month header bar.

Is there a way to fix this problem without recreating a caldroid fragment instance?
