### ISSUE TITLE
Limit the scroll 

### ISSUE THREAD

**Issue by birfincankafein** [roomorama/Caldroid#299]
How can I limit the scroll with setMinDate and setMaxDate? 

This functions does only deactive the dates but I want to user can't scroll more than min max dates.

**Comment by subediaayush** [comment]
Yes, limiting the scrolling option would be nice

**Comment by flooreeda** [comment]
I would like this feature too.

**Comment by rameshvoltella** [comment]
how to limit the scroll, please fix this issue soon

**Comment by thomasdao** [comment]
Guys if you really *need* it, please send me a PR. I am no longer work actively on this projecy

**Comment by rameshvoltella** [comment]
can u tell why the prev mouth still show even if we limit mindate and max date?

**Comment by thomasdao** [comment]
@rameshvoltella The swiping is handled by an infinite view pager. You can look at the source code. I don't have a need for this feature so welcome anyone can work on it. And if you are not happy with that, well there're many other open sources project

**Comment by birfincankafein** [comment]
in the source code, go to infinitelimitpager and set page limit int_max to whatever you want. if you limit it programmatically, add method to fragment and set viewpager max page count. Use min date and max date to calculate page size.

**Comment by birfincankafein** [comment]
@thomasdao please be nice. we are helping you to improve this library. I did it but I did too much changes for myself. If you say I get it from your edit I can send you my code. 

And again, thank you for developed this awesome library. Good day.

**Comment by thomasdao** [comment]
@birfincankafein first of all, if I offended anyone, then I apologise. Don't take things personal, because I don't mean to.

Now to your point. If you think you are helping me, then you're wrong. I develop this library 2 years ago and I no longer use it for very long time. I moved on with other apps and other requirements. However I still develop and maintain this library because I think others may benefit from it. If you want to contribute, you are helping other developers, not me. If you don't want, it's perfectly fine too, no one is judging you for that.

I of course also don't need you to send me your code. This is what open source is all about - you have freedom to do whatever fit to the license, and of course to choose different project if you like. I am okay for that.

About Caldroid -  since I no longer use it, and kind of lost interest for it, I also don't actively develop any other feature anymore. If anyone like to have more feature, then they're welcomed to work on it, and if they like, send me a PR, or if they don't like, push it to their own fork.

Hope this clarify things. And hope you don't take things personal too.
