### ISSUE TITLE
Hide today's day highlighter in calendar(red color box)

### ISSUE THREAD

**Issue by sandeeptengale** [roomorama/Caldroid#347]
How to disable showing the current date with the red square box? I don't need to highlight today's date in my calendar with red box. 

Is there any method to hide or set color to that box. Please help me

**Comment by Chris59160** [comment]
The only way I found to do that code in my onCreate :

`Date currentDate = new Date();
Drawable drawable = ResourcesCompat.getDrawable(getResources(), R.drawable.caldroid_not_selected_active_cell, null);
caldroidFragment.setBackgroundDrawableForDate(drawable, currentDate);`

The "R.drawable.caldroid_not_selected_active_cel" is a simple white shaped rectangle.

Pretty annoying, because even trying to customize the cell and theme with a style...it completely ignores some bits.

If you have found a way to do it via style/theme only, please post your answer :-)
